spring:
  application:
    name: guest-service
  datasource:
    url: jdbc:mysql://mysql:3306/booking-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:hibernate:dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080