version: '3.1'

services:

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "${DISCOVERY_SERVER_PORT}:8761"
    expose:
      - "${DISCOVERY_SERVER_PORT}"
    env_file:
      - .env

  api-gateway:
    restart: unless-stopped
    build:
      context: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    env_file:
      - .env

  location-service:
    restart: unless-stopped
    build:
      context: ./location-service
    ports:
      - "${LOCATION_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - discovery-server
      - mysql

  guest-service:
    restart: unless-stopped
    build:
      context: ./guests-service
    ports:
      - "${GUEST_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - discovery-server
      - mysql

  comment-service:
    restart: unless-stopped
    build:
      context: ./comment-service
    ports:
      - "${COMMENT_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - discovery-server
      - mongo

  hotel-service:
    restart: unless-stopped
    build:
      context: ./hotel-service
    ports:
      - "${HOTEL_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - discovery-server
      - comment-service
      - guest-service

  auth-service:
    restart: unless-stopped
    build:
      context: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongo
      - discovery-server
    # --------------------- DATABASE  --------------------------------------
  mysql:
    image: mysql:8.0.35-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking-db
    ports:
      - "${SQL_DB_PORT}:3306"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${MONGO_DB_PORT}:27017"

  #----------------- DATABASE_GUI ------------------------

  adminer:
    image: adminer
    restart: always
    ports:
      - "${SQL_GUI_PORT}:8080"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_GUI_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/