version: '3.1'

services:

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "${DISCOVERY_SERVER_PORT}:8761"
    env_file:
      - .env

  api-gateway:
    restart: unless-stopped
    build:
      context: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    env_file:
      - .env

  location-service:
    restart: unless-stopped
    build:
      context: ./location-service
    env_file:
      - .env
    depends_on:
      - discovery-server
      - mysql
    # --------------------- DATABASE  --------------------------------------
  mysql:
    image: mysql:8.0.35-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking-db
    ports:
      - "3306:3306"

  #----------------- DATABASE_GUI ------------------------

  adminer:
    image: adminer
    restart: always
    ports:
      - "${SQL_GUI_PORT}:8080"

  #--------------------KAFKA--------------------------

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1