version: '3.1'

services:
      # --------------------- DATABASE  --------------------------------------
  mysql:
    image: mysql:8.0.35-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking-db
    ports:
      - "${SQL_DB_PORT}:3306"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${MONGO_DB_PORT}:27017"

  #----------------- DATABASE_GUI ------------------------

  adminer:
    image: adminer
    restart: always
    ports:
      - "${SQL_GUI_PORT}:8080"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_GUI_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/