version: '3.1'

services:
  mysql:
    image: mysql:8.0.35-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8180:8080"